In [1]:
import camelot

In [2]:
table = camelot.read_pdf('../../data/08-10.pdf',pages = '2')

FileNotFoundError: [Errno 2] No such file or directory: '../../data/08-10.pdf'

In [8]:
df1 = table[0].df
df1

                                              0      1
0   District Distribution of Confirmed Patients
1                               HEALTH DISTRICT  Count
2                                       COLOMBO    160
3                                       GAMPAHA     38
4                                      PUTTALAM     35
5                                      KALUTARA     34
6                                  ANURADHAPURA     20
7                                         KANDY     16
8                                    KURUNEGALA     11
9                                   POLONNARUWA     13
10                                       JAFFNA      7
11                                    RATNAPURA      6
12                                      KEGALLE      4
13                                   MONERAGALA      4
14                                     KALMUNAI      2
15                                       MATALE      2
16                                        GALLE      2
17                                       AMPARA      2
18                                      BADULLA      1
19                                       MATARA      1
20                                   BATTICOLOA      1
21                                   HAMBANTOTA      1
22                                      VAVUNIA      0
23                                  TRINCOMALEE      0
24                                  NUWARAELIYA      0
25                                  KILINOCHCHI      0
26                                       MANNAR      0
27                                    MULLATIVU      0
28                                                 000
29       QUARANTINE CENTERS (Overseas Arrivals)   1420
30       QUARANTINE CENTERS (Local Communities)     78
31                                         NAVY    906
32                                 OTHER FORCES     17
33                                   FOREIGNERS    100
34                      Kandakadu Rehab. Center    597
35                              Welikada Prison      1
36               Minuwangoda/Peliyagoda cluster   6312
37                                        Total  9791*

In [9]:
df2 = table[1].df
df2

,0,1,2,3,4,5,6,7,8
0,,,,,,,,,
1,,Number of COVID -19 suspected patients – 444#,,,,,,,
2,,Hospital,Total suspected up to \nnow,,,Today 10am,,,
3,,,SL,Forei.,Total,SL,Forei.,Total,
4,,NIID,1120,76,1184,16,0,16,
5,,NHSL,1467,16,1481,48,0,48,
6,,TH Ragama,1593,5,1598,35,0,35,
7,,TH Karapitiya,521,26,547,12,0,12,
8,,TH A'pura,1365,2,1367,16,0,16,
9,,TH Kurun.,883,1,884,12,0,12,
10,,TH Jaffna,217,2,219,5,0,5,
11,,NH Kandy,248,6,254,0,0,0,
12,,TH Batti.,300,0,300,4,0,4,
13,,DGH Gampaha,560,4,564,27,0,27,
14,,DGH Negombo,1465,15,1480,30,0,30,
15,,TH Rathn.,468,0,468,6,0,6,
16,,PGH Badulla,151,2,153,6,0,6,
17,,LRH,220,0,220,9,0,9,
18,,DMH,550,1,551,11,0,11,
19,,DGH Polon’wa,657,6,663,6,0,6,
20,,TH Kalubowila,568,5,573,19,0,19,
21,,Castle St TH,574,0,574,7,0,7,
22,,BH Ham’thota,382,2,384,0,0,0,
23,,BH Mona’gala,225,0,225,5,0,5,
24,,BH Welikanda,69,1,70,0,0,0,
25,,DGH Kaluthara,806,2,808,10,0,10,
26,,Chest H. Welisara,600,2,602,28,0,28,
27,,Colombo East Base \nHospital,70,0,70,30,0,30,
28,,G.H. Chilaw,3136,1,3137,24,0,24,
29,,G.H. Matara,158,2,160,0,0,0,
30,,KDU Hospital,2009,0,2009,2,0,2,
31,,G.H. Vavunia,201,0,201,1,0,1,
32,,B.H. Marawila,237,1,238,3,0,3,
33,,S.J.Pura TH,3392,2,3394,58,0,58,
34,,BH Theldeniya,37,0,37,12,0,12,
35,,BH Tangalle,15,0,15,2,0,2,
36,,Total,Incorrect to total as transfers \ncounts in bo...,,,444,0,444#,
37,"Source: Epidemiology Unit, Disease Surveillanc...",,,,,,,,

In [10]:
df3 = table[2].df
df3

,0,1,2,3
0,,District Distribution of Confirmed Patients,,
1,,HEALTH DISTRICT,Count,
2,,COLOMBO,160,
3,,GAMPAHA,38,
4,,PUTTALAM,35,
5,,KALUTARA,34,
6,,ANURADHAPURA,20,
7,,KANDY,16,
8,,KURUNEGALA,11,
9,,POLONNARUWA,13,
10,,JAFFNA,7,
11,,RATNAPURA,6,
12,,KEGALLE,4,
13,,MONERAGALA,4,
14,,KALMUNAI,2,
15,,MATALE,2,
16,,GALLE,2,
17,,AMPARA,2,
18,,BADULLA,1,
19,,MATARA,1,
20,,BATTICOLOA,1,
21,,HAMBANTOTA,1,
22,,VAVUNIA,0,
23,,TRINCOMALEE,0,
24,,NUWARAELIYA,0,
25,,KILINOCHCHI,0,
26,,MANNAR,0,
27,,MULLATIVU,0,
28,,,000,
29,,QUARANTINE CENTERS (Overseas Arrivals),1420,
30,,QUARANTINE CENTERS (Local Communities),78,
31,,NAVY,906,
32,,OTHER FORCES,17,
33,,FOREIGNERS,100,
34,,Kandakadu Rehab. Center,597,
35,,Welikada Prison,1,
36,,Minuwangoda/Peliyagoda cluster,6312,
37,,Total,9791*,
38,Note: District categorization has been done c...,,,

In [16]:
import pandas as pd
import camelot
from os import path
fin_df = pd.DataFrame()

In [17]:
def fill_csv(f_name):
    tables = camelot.read_pdf('../../data/daily_pdf/'+f_name+'.pdf',pages = '2')
    dist_table = tables[0].df
    print(dist_table.shape)
    # hosp_table = table[1].df
    # today_df = dist_table.iloc[2:27,:]
    # today_df = pd.concat(pd.Series(data='2020-'+f_name,index=range(25),dtype='datetime64[ns]'),today_df,axis=1)
    # return today_df

In [18]:
for i in range(4,11):
    for j in range(1,32):
        file_name = '{:02d}-{:02d}'.format(i,j)
        if (path.exists('../../data/daily_pdf/'+file_name+'.pdf')):
            fill_csv(file_name)

(63, 14)
(63, 14)
(63, 14)
(59, 14)
(59, 14)
(59, 14)
(59, 14)
(58, 14)
(58, 14)
(63, 14)
(63, 14)
(62, 14)
(62, 14)
(63, 14)
(64, 14)
(64, 14)
(63, 14)
(63, 14)
(63, 14)
(63, 14)
(64, 14)
(64, 14)
(64, 14)
(65, 14)
(65, 14)
(65, 14)
(67, 14)
(67, 14)
(67, 14)
(67, 14)
(66, 14)
(66, 14)
(66, 14)
(69, 14)
(68, 14)
(67, 14)
(66, 14)
(67, 14)
(66, 14)
(66, 14)
(66, 14)
(66, 14)
(66, 14)
(66, 14)
(66, 14)
(67, 14)
(67, 14)
(67, 14)
(67, 14)
(67, 14)
(67, 14)
(67, 14)
(67, 14)
(67, 14)
(67, 14)
(67, 14)
(67, 14)
(67, 14)

KeyboardInterrupt:

In [13]:
f_name = '09-10'
tables = camelot.read_pdf('../../data/daily_pdf/'+f_name+'.pdf',pages = '2')
dist_table = tables[0].df
dist_table

# hosp_table = table[0].df
# today_df = dist_table.iloc[2:27,:]
# ser = pd.Series(data='2020-'+f_name,index=range(25),dtype='datetime64[ns]')
# today_df = pd.concat(ser,today_df,axis=1)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,"Source: Epidemiology Unit, Disease Surveillanc...",,,,,,,,,,,,,
1,,Number of COVID -19 suspected patients – 70#,,,,,,,,,,District Distribution of Confirmed Patients,,
2,,Hospital,Total suspected up to \nnow,,,Today 10am,,,,,,HEALTH DISTRICT,Count,
3,,,SL,Forei.,Total,SL,Forei.,Total,,,,,,
4,,,,,,,,,,,,COLOMBO,160,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,,,,,,,,,,,,FOREIGNERS,47,
60,,,,,,,,,,,,Kandakadu Rehab. Center,596,
61,,,,,,,,,,,,Welikada Prison,1,
62,,,,,,,,,,,,Total,3147*,
63,,,,,,,,,,,Note: District categorization has been done c...,,,